### ISSUE TITLE
Failed deploy

### ISSUE THREAD

**Issue by siritami** [yuchanns/warpflare#1]
I can't deploy, already added CLOUDFLARE_ACCOUNT_ID, CLOUDFLARE_API_TOKEN secret following Readme. Herre is deploy logs:
https://github.com/siritami/warpflare/actions/runs/8326540052/job/22782412521

**Comment by yuchanns** [comment]
`SECRET_KEY` is needed as well.

**Comment by siritami** [comment]
I already added it
With new commit have a new error...
  ✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/warp) failed.
    binding DATABASE of type d1 must have a database that already exists. Use wrangler or the UI to create the database. [code: 10021]
https://github.com/siritami/warpflare/actions/runs/8326956557/job/22783632166

**Comment by yuchanns** [comment]
Oops! We have missed an important step for the new worker, creating a database. 
Currently, I can not find a good way to make it automatic so You have to create it from Dashboard and replace it with the file `wrangler.toml`.

- Follow the picture and create a database named `warp-db`:
	![image](https://github.com/yuchanns/warpflare/assets/25029451/08bb55a4-41aa-4d87-b3b5-30a5f097e079)
- You should get a **Database ID** after d1 is created, Paste it into the `database_id` field of [[d1_databases]] in the `wrangler.toml` file.

Done.

**Comment by yuchanns** [comment]
Should fixed now.

**Comment by siritami** [comment]
Thank you so much, it successful deploy now
