### ISSUE TITLE
感谢大佬，clash提示订阅解析错误

### ISSUE THREAD

**Issue by FANYT** [yuchanns/warpflare#10]
ERR [Config] configuration file test failed error=proxy 0: ParseAddr("172.16.0.2/32"): unexpected character (at "/32") path=/tmp/yaml_sub_tmp_config.yaml

**Comment by FANYT** [comment]
![image](https://github.com/yuchanns/warpflare/assets/9249921/865561d3-240b-43e7-b41d-2d1ddd7f53c1)

**Comment by lry0829** [comment]
一样的问题，不知道你解决了没

**Comment by KaiWenRui** [comment]
+1，还没解决

**Comment by wikiq** [comment]
> 一样的问题，不知道你解决了没

Clash for Windows好像默认不支持wireguard吧

**Comment by mumaxiaozi** [comment]
> ERR [Config] configuration file test failed error=proxy 0: ParseAddr("172.16.0.2/32"): unexpected character (at "/32") path=/tmp/yaml_sub_tmp_config.yaml

可以下载了文件，把里面的 172.16.0.2/32  替换成了 172.16.0.2   即删除 /32

**Comment by yuchanns** [comment]
#16

**Comment by FANYT** [comment]
可以了，谢谢大佬
