### ISSUE TITLE
Unauthorized解决

### ISSUE THREAD

**Issue by 320656** [yuchanns/warpflare#13]
要是你们在浏览器输入url得到Unauthorized，就是你勾子token把"${}"加上去了，删除就好了
浏览器得到Unsupported sub type是对的
![28ABC688FFE4E8076B32D30F65122456](https://github.com/yuchanns/warpflare/assets/111040018/20fc6c79-98e5-4f5e-a99f-f03cdc5e04d8)

**Comment by ynsc133** [comment]
warp->开始获取订阅内容
2024/05/16 07:53:33 DNS accepted udp:1.1.1.1:53 [xray.system.77fgg54b-8876-467r-9345-cghhgffg7801 >> proxy]
2024/05/16 07:53:37 DNS accepted udp:8.8.8.8:53 [xray.system.77fgg54b-8876-467r-9345-cghhgffg7801 >> proxy]
2024/05/16 07:53:41 127.0.0.1:50457 accepted //warp.try.workers.dev:443 [http >> proxy]
warp->The SSL connection could not be established, see inner exception.
warp-> Received an unexpected EOF or 0 bytes from the transport stream.
2024/05/16 07:53:43 DNS accepted udp:1.1.1.1:53 [xray.system.77fgg54b-8876-467r-9345-cghhgffg7801 >> proxy]
2024/05/16 07:53:47 DNS accepted udp:8.8.8.8:53 [xray.system.77fgg54b-8876-467r-9345-cghhgffg7801 >> proxy]
2024/05/16 07:53:51 127.0.0.1:50465 accepted //warp.try.workers.dev:443 [http >> proxy]
warp->The SSL connection could not be established, see inner exception.
warp->The SSL connection could not be established, see inner exception.
2024/05/16 07:53:53 DNS accepted udp:1.1.1.1:53 [xray.system.77fgg54b-8876-467r-9345-cghhgffg7801 >> proxy]
2024/05/16 07:53:57 DNS accepted udp:8.8.8.8:53 [xray.system.77fgg54b-8876-467r-9345-cghhgffg7801 >> proxy]
2024/05/16 07:54:01 127.0.0.1:50473 accepted //warp.try.workers.dev:443 [http >> proxy]
warp->The SSL connection could not be established, see inner exception.
warp->The SSL connection could not be established, see inner exception.
warp->获取订阅内容成功
warp->导入订阅内容失败

没有任何节点。这个要怎么办？
私密信息已经处理。请放心！
谢谢！
